---
---
## Metodologia

Como comentado, utilizei um aplicativo para a contagem de calorias, o *fatsecret*, que é gratuito e possui boa parte dos alimentos que utilizei, em alguns casos fiz algumas aproximações quando não encontrava exatamente o mesmo alimento ou quando por algum motivo não conseguia fazer a pesagem.

Esse estudo está longe de ser algo científico e rigoroso, mas é algo perto da minha realidade e imagino que de muitos outros que apenas se sentem insatisfeitos com seu peso e querem mudar um pouco sua relação com seu corpo.

A pesagem foi feita sempre na mesma balança comum que tenho em casa, e sempre praticamente no mesmo horário, ao acordar de manhã em jejum.

A avaliação inicial (cujos dados serão avaliados no futuro) foi no dia 07/11/2023 e a avaliação final no dia 15/01/2024, totalizando dois meses e uma semana. Mas, para ser mais honesto, eu havia começado antes da avaliação inicial, acho que uma data justa seria o dia 03/10/2023, onde comecei a pesar os alimentos, porém foi um período de adaptação, e considero que o início foi mesmo após a avaliação, pois já estava em déficit calórico e foi quando tirei as medidas.

Outra coisa importante a salientar é que faço exercícios físicos regularmente, frequento à academia entre 4-5x na semana, e nas últimas semanas, do dia 02/jan/2024 em diante, tenho feito 6x, ou exercício físico, ou exercícios aeróbicos como elíptico ou bicicleta.

Finalizando então a metodologia, vamos para os dados!
